#pragma once
#ifndef MENUSTATE_H
#define MENUSTATE_H

enum class MenuState : int
{
	SHOW_CHAT_MENU = 3,
	SHOW_BOTTOM_MENU = 5,
	SHOW_MAP_SORCERER_SCORES = 7,
	SHOW_MAP_BOTTOM_MENU = 8,
	SHOW_IN_GAME_OPTIONS = 9,
	SHOW_MAP_GAME_OPTIONS = 0xB,
	SHOW_VOLUME_OPTIONS = 10,
	SHOW_MAP_VOLUME_OPTIONS = 0xC,
	SHOW_OK_CANCEL_OPTIONS = 13,
	SHOW_MAP_OK_CANCEL_OPTIONS = 0xE,
};

#endif //MENUSTATE_H