#pragma once
#ifndef RESOURCE_TYPE_H
#define RESOURCE_TYPE_H

enum class ResourceType
{
	TEXTURE_LOADED,
	TEXTURE_DISPOSED,
	SPRITE_LOADED,
	SPRITE_DISPOSED,
	POLYGONS_UPDATED,
	POLYGONS_DISPOSED
};

#endif //RESOURCE_TYPE_H