name: MSBuild CI

on: 
  push:
    branches:
      [ master, development ]
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  GITHUB_REF_NAME: 'release-1.2.3-alpha'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [x86, x64]

    steps:
     - name: Extract version
        shell: bash
        run: |
          if [[ "$GITHUB_REF_NAME" =~ ([0-9]+(\.[0-9]+)+) ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "No version found in ref_name: $GITHUB_REF_NAME"
            exit 1
          fi

      - name: Split version
        shell: bash
        run: |
          IFS='.' read -r MAJOR MINOR REVISION BUILD <<< "$VERSION"
          echo "MAJOR=$MAJOR" >> "$GITHUB_ENV"
          echo "MINOR=$MINOR" >> "$GITHUB_ENV"
          echo "REVISION=$REVISION" >> "$GITHUB_ENV"
          echo "BUILD=${BUILD:-0}" >> "$GITHUB_ENV"
          
      - name: Prepare folders
        shell: pwsh
        run: |
          $arch = "${{ matrix.arch }}"
          
          # Replace version
          (Get-Content remc2-installer\Program.cs).Replace('Version(0, 0, 0, 0)', "Version($env:MAJOR, $env:MINOR, $env:REVISION, $env:BUILD)") | Set-Content remc2-installer\Program.cs